# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-24 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weixianjiashi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='weixianjiashi',
        ),
    ]
