# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-24 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixianjiashi', '0003_weixianjiashi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weixianjiashi',
            name='Alcohol',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='weixianjiashi',
            name='AwardID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='weixianjiashi',
            name='IndictmentID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='weixianjiashi',
            name='Judge',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
