# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-24 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixianjiashi', '0004_auto_20171124_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='weixianjiashi',
            name='Dentention_huanxing',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='weixianjiashi',
            name='FixtedTerm_huanxing',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='weixianjiashi',
            name='Surveillans_huanxing',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
