# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-10 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='weixianjiashi',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=50)),
            ],
        ),
    ]
