# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-10 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiaotongzhaoshi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weixianjiashi',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weixianjiashi',
            name='huizui',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='weixianjiashi',
            name='ligong',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='weixianjiashi',
            name='pedigree',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='weixianjiashi',
            name='recividist',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='weixianjiashi',
            name='renzui',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='weixianjiashi',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='weixianjiashi',
            name='tanbai',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='weixianjiashi',
            name='zishou',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='weixianjiashi',
            name='filename',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
