# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-10 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiaotongzhaoshi', '0003_auto_20171110_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weixianjiashi',
            name='huizui',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='weixianjiashi',
            name='ligong',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='weixianjiashi',
            name='pedigree',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='weixianjiashi',
            name='recividist',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='weixianjiashi',
            name='renzui',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='weixianjiashi',
            name='tanbai',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='weixianjiashi',
            name='zishou',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
