# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiaotongzhaoshi', '0004_auto_20171110_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='weixianjiashi',
            name='baofeiche',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='weixianjiashi',
            name='diandongchejidong',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='weixianjiashi',
            name='huoche',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='weixianjiashi',
            name='jiaoche',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='weixianjiashi',
            name='keche',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='weixianjiashi',
            name='motuoche',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
