# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-18 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiaotongzhaoshi', '0005_auto_20171117_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='jiaotongzhaoshi',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('filename', models.CharField(blank=True, max_length=50, null=True)),
                ('panjueshuId', models.CharField(blank=True, max_length=30, null=True)),
                ('qisushuId', models.CharField(blank=True, max_length=30, null=True)),
                ('shenpanshijian', models.CharField(blank=True, max_length=30, null=True)),
                ('shenpanyuan', models.CharField(blank=True, max_length=30, null=True)),
                ('sheng', models.CharField(blank=True, max_length=30, null=True)),
                ('shi', models.CharField(blank=True, max_length=30, null=True)),
                ('xian', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('pedigree', models.CharField(blank=True, max_length=1, null=True)),
                ('recividist', models.CharField(blank=True, max_length=1, null=True)),
                ('zishou', models.CharField(blank=True, max_length=1, null=True)),
                ('tanbai', models.CharField(blank=True, max_length=1, null=True)),
                ('ligong', models.CharField(blank=True, max_length=1, null=True)),
                ('renzui', models.CharField(blank=True, max_length=1, null=True)),
                ('huizui', models.CharField(blank=True, max_length=1, null=True)),
                ('keche', models.CharField(blank=True, max_length=1, null=True)),
                ('motuoche', models.CharField(blank=True, max_length=1, null=True)),
                ('huoche', models.CharField(blank=True, max_length=1, null=True)),
                ('jiaoche', models.CharField(blank=True, max_length=1, null=True)),
                ('diandongchejidong', models.CharField(blank=True, max_length=1, null=True)),
                ('baofeiche', models.CharField(blank=True, max_length=1, null=True)),
                ('taopaiche', models.CharField(blank=True, max_length=1, null=True)),
                ('qitajidongcheliang', models.CharField(blank=True, max_length=1, null=True)),
                ('feijidongche', models.CharField(blank=True, max_length=1, null=True)),
                ('zhuizhujingshi', models.CharField(blank=True, max_length=1, null=True)),
                ('jiujia', models.CharField(blank=True, max_length=1, null=True)),
                ('zuijia', models.CharField(blank=True, max_length=1, null=True)),
                ('chaosu', models.CharField(blank=True, max_length=1, null=True)),
                ('chaozai', models.CharField(blank=True, max_length=1, null=True)),
                ('weixianpinyunshu', models.CharField(blank=True, max_length=1, null=True)),
                ('guanzhi', models.CharField(blank=True, max_length=20, null=True)),
                ('juyi', models.CharField(blank=True, max_length=20, null=True)),
                ('youqituxing', models.CharField(blank=True, max_length=20, null=True)),
                ('wuqituxing', models.CharField(blank=True, max_length=20, null=True)),
                ('sixing', models.CharField(blank=True, max_length=1, null=True)),
                ('zhongshenjianjin', models.CharField(blank=True, max_length=1, null=True)),
                ('fajin', models.CharField(blank=True, max_length=20, null=True)),
                ('moshoucaichan', models.CharField(blank=True, max_length=1, null=True)),
                ('boduozhengzhiquanli', models.CharField(blank=True, max_length=1, null=True)),
                ('quzhuchujing', models.CharField(blank=True, max_length=1, null=True)),
                ('shoujiaofeifacaichan', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='weixianjiashi',
        ),
    ]
