# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-24 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiaotongzhaoshi', '0006_auto_20171118_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jiaotongzhaoshi',
            name='age',
        ),
        migrations.RemoveField(
            model_name='jiaotongzhaoshi',
            name='boduozhengzhiquanli',
        ),
        migrations.RemoveField(
            model_name='jiaotongzhaoshi',
            name='chaosu',
        ),
        migrations.RemoveField(
            model_name='jiaotongzhaoshi',
            name='chaozai',
        ),
        migrations.RemoveField(
            model_name='jiaotongzhaoshi',
            name='fajin',
        ),
        migrations.RemoveField(
            model_name='jiaotongzhaoshi',
            name='guanzhi',
        ),
        migrations.RemoveField(
            model_name='jiaotongzhaoshi',
            name='juyi',
        ),
        migrations.RemoveField(
            model_name='jiaotongzhaoshi',
            name='moshoucaichan',
        ),
        migrations.RemoveField(
            model_name='jiaotongzhaoshi',
            name='panjueshuId',
        ),
        migrations.RemoveField(
            model_name='jiaotongzhaoshi',
            name='qisushuId',
        ),
        migrations.RemoveField(
            model_name='jiaotongzhaoshi',
            name='quzhuchujing',
        ),
        migrations.RemoveField(
            model_name='jiaotongzhaoshi',
            name='sheng',
        ),
        migrations.RemoveField(
            model_name='jiaotongzhaoshi',
            name='shenpanshijian',
        ),
        migrations.RemoveField(
            model_name='jiaotongzhaoshi',
            name='shenpanyuan',
        ),
        migrations.RemoveField(
            model_name='jiaotongzhaoshi',
            name='shi',
        ),
        migrations.RemoveField(
            model_name='jiaotongzhaoshi',
            name='shoujiaofeifacaichan',
        ),
        migrations.RemoveField(
            model_name='jiaotongzhaoshi',
            name='sixing',
        ),
        migrations.RemoveField(
            model_name='jiaotongzhaoshi',
            name='weixianpinyunshu',
        ),
        migrations.RemoveField(
            model_name='jiaotongzhaoshi',
            name='wuqituxing',
        ),
        migrations.RemoveField(
            model_name='jiaotongzhaoshi',
            name='xian',
        ),
        migrations.RemoveField(
            model_name='jiaotongzhaoshi',
            name='youqituxing',
        ),
        migrations.RemoveField(
            model_name='jiaotongzhaoshi',
            name='zhongshenjianjin',
        ),
        migrations.RemoveField(
            model_name='jiaotongzhaoshi',
            name='zhuizhujingshi',
        ),
        migrations.AddField(
            model_name='jiaotongzhaoshi',
            name='Abscond',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='jiaotongzhaoshi',
            name='Alcohol',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='jiaotongzhaoshi',
            name='AmountOfCompensation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jiaotongzhaoshi',
            name='AwardID',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jiaotongzhaoshi',
            name='CaptureIllegalProperty',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jiaotongzhaoshi',
            name='City',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jiaotongzhaoshi',
            name='ConfiscationOfProperty',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jiaotongzhaoshi',
            name='CountyDistrict',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jiaotongzhaoshi',
            name='DangerousCargo',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jiaotongzhaoshi',
            name='Death',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jiaotongzhaoshi',
            name='DeathCausedByAbscond',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='jiaotongzhaoshi',
            name='DeathNum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jiaotongzhaoshi',
            name='DegreeOfPropertyLosses',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jiaotongzhaoshi',
            name='Dentention',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jiaotongzhaoshi',
            name='Deportation',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jiaotongzhaoshi',
            name='DeprivalOfPoliticalRight',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jiaotongzhaoshi',
            name='EducationalBackground',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='jiaotongzhaoshi',
            name='Fine',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jiaotongzhaoshi',
            name='FixtedTerm',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jiaotongzhaoshi',
            name='IncidentAge',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jiaotongzhaoshi',
            name='IndictmentID',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jiaotongzhaoshi',
            name='InjuredNum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jiaotongzhaoshi',
            name='Judge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jiaotongzhaoshi',
            name='LifeImprisonment',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jiaotongzhaoshi',
            name='OverLoad',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jiaotongzhaoshi',
            name='OverSpeed',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jiaotongzhaoshi',
            name='Province',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jiaotongzhaoshi',
            name='Reaing',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jiaotongzhaoshi',
            name='Surveillans',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jiaotongzhaoshi',
            name='TrialTime',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jiaotongzhaoshi',
            name='UnfixtedTerm',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jiaotongzhaoshi',
            name='VictimUnderstanding',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='jiaotongzhaoshi',
            name='confirmationOfResponsibility',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
