# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-24 08:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jiaotongzhaoshi', '0007_auto_20171124_1625'),
    ]

    operations = [
        migrations.DeleteModel(
            name='jiaotongzhaoshi',
        ),
    ]
