# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-24 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiaotongzhaoshi', '0009_jiaotongzhaoshi'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiaotongzhaoshi',
            name='Dentention_huanxing',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jiaotongzhaoshi',
            name='FixtedTerm_huanxing',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jiaotongzhaoshi',
            name='Surveillans_huanxing',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
