# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-24 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiaotongzhaoshi', '0010_auto_20171124_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jiaotongzhaoshi',
            name='Judge',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
