# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-24 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiaotongzhaoshi', '0011_auto_20171124_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jiaotongzhaoshi',
            name='confirmationOfResponsibility',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
