# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-24 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiaotongzhaoshi', '0014_auto_20171124_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jiaotongzhaoshi',
            name='AmountOfCompensation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
