# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-28 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiaotongzhaoshi', '0016_auto_20171124_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jiaotongzhaoshi',
            name='filename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
